# 应用名称
spring:
  application:
    name: nowcoder
  # 模板编码
  thymeleaf:
    encoding: UTF-8
  datasource:
    username: root
    password: 4587889
    url: jdbc:mysql://localhost:3306/nowcoder?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
#    邮件
  mail:
    host: smtp.qq.com
    username: 2582130596@qq.com
    password: witdneatweradjab
# 应用服务 WEB 访问端口
server:
  port: 9099
  servlet:
    context-path: /community
#域名地址
community:
  path:
    domain: http://localhost:9099
    upload: D:/Desktop/nowcoder

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl